
site_name: Tcl/Tk
site_url: https://www.tcl.tk/man

theme:
  name: readthedocs
  highlightjs: false

  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: 
    - index.md
    - ItclCmd:
      - ItclCmd/index.md
    - ItclLib:
      - ItclLib/index.md
    - Keywords:
      - Keywords/index.md
    - SqliteCmd:
      - SqliteCmd/index.md
    - TclCmd:
      - TclCmd/index.md
    - TclLib:
      - TclLib/index.md
    - TdbcCmd:
      - TdbcCmd/index.md
    - TdbcLib:
      - TdbcLib/index.md
    - TdbcmysqlCmd:
      - TdbcmysqlCmd/index.md
    - TdbcodbcCmd:
      - TdbcodbcCmd/index.md
    - TdbcpostgresCmd:
      - TdbcpostgresCmd/index.md
    - ThreadCmd:
      - ThreadCmd/index.md
    - TkCmd:
      - TkCmd/index.md
    - TkLib:
      - TkLib/index.md
    - UserCmd:
      - UserCmd/index.md
